// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: bff.proto

package bff

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User info messages
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_bff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{0}
}

type GetUserInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sub               string                 `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
	EmailVerified     bool                   `protobuf:"varint,2,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PreferredUsername string                 `protobuf:"bytes,4,opt,name=preferred_username,json=preferredUsername,proto3" json:"preferred_username,omitempty"`
	GivenName         string                 `protobuf:"bytes,5,opt,name=given_name,json=givenName,proto3" json:"given_name,omitempty"`
	FamilyName        string                 `protobuf:"bytes,6,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	Email             string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_bff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserInfoResponse) GetSub() string {
	if x != nil {
		return x.Sub
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *GetUserInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserInfoResponse) GetPreferredUsername() string {
	if x != nil {
		return x.PreferredUsername
	}
	return ""
}

func (x *GetUserInfoResponse) GetGivenName() string {
	if x != nil {
		return x.GivenName
	}
	return ""
}

func (x *GetUserInfoResponse) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Chat messages
type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	McpServerName string                 `protobuf:"bytes,4,opt,name=mcp_server_name,json=mcpServerName,proto3" json:"mcp_server_name,omitempty"`
	IsNewChat     bool                   `protobuf:"varint,5,opt,name=is_new_chat,json=isNewChat,proto3" json:"is_new_chat,omitempty"`
	FileUrl       string                 `protobuf:"bytes,6,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	RawToolResult string                 `protobuf:"bytes,7,opt,name=raw_tool_result,json=rawToolResult,proto3" json:"raw_tool_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_bff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChatRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatRequest) GetMcpServerName() string {
	if x != nil {
		return x.McpServerName
	}
	return ""
}

func (x *ChatRequest) GetIsNewChat() bool {
	if x != nil {
		return x.IsNewChat
	}
	return false
}

func (x *ChatRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *ChatRequest) GetRawToolResult() string {
	if x != nil {
		return x.RawToolResult
	}
	return ""
}

type ChatEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "content", "tool_call", "tool_result", "error", "done"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // Text content for "content" events
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       // JSON data for tool calls etc.
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`     // Error message for "error" events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatEvent) Reset() {
	*x = ChatEvent{}
	mi := &file_bff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatEvent) ProtoMessage() {}

func (x *ChatEvent) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatEvent.ProtoReflect.Descriptor instead.
func (*ChatEvent) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{3}
}

func (x *ChatEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChatEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ChatEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopChatRequest) Reset() {
	*x = StopChatRequest{}
	mi := &file_bff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopChatRequest) ProtoMessage() {}

func (x *StopChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopChatRequest.ProtoReflect.Descriptor instead.
func (*StopChatRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{4}
}

func (x *StopChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type StopChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopChatResponse) Reset() {
	*x = StopChatResponse{}
	mi := &file_bff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopChatResponse) ProtoMessage() {}

func (x *StopChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopChatResponse.ProtoReflect.Descriptor instead.
func (*StopChatResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{5}
}

func (x *StopChatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GenerateTitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTitleRequest) Reset() {
	*x = GenerateTitleRequest{}
	mi := &file_bff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTitleRequest) ProtoMessage() {}

func (x *GenerateTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTitleRequest.ProtoReflect.Descriptor instead.
func (*GenerateTitleRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{6}
}

func (x *GenerateTitleRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *GenerateTitleRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type GenerateTitleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GeneratedTitle string                 `protobuf:"bytes,1,opt,name=generated_title,json=generatedTitle,proto3" json:"generated_title,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateTitleResponse) Reset() {
	*x = GenerateTitleResponse{}
	mi := &file_bff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTitleResponse) ProtoMessage() {}

func (x *GenerateTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTitleResponse.ProtoReflect.Descriptor instead.
func (*GenerateTitleResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{7}
}

func (x *GenerateTitleResponse) GetGeneratedTitle() string {
	if x != nil {
		return x.GeneratedTitle
	}
	return ""
}

func (x *GenerateTitleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Chat query messages
type GetChatIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatIdsRequest) Reset() {
	*x = GetChatIdsRequest{}
	mi := &file_bff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatIdsRequest) ProtoMessage() {}

func (x *GetChatIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatIdsRequest.ProtoReflect.Descriptor instead.
func (*GetChatIdsRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{8}
}

type GetChatIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatMetadata        `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatIdsResponse) Reset() {
	*x = GetChatIdsResponse{}
	mi := &file_bff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatIdsResponse) ProtoMessage() {}

func (x *GetChatIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatIdsResponse.ProtoReflect.Descriptor instead.
func (*GetChatIdsResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{9}
}

func (x *GetChatIdsResponse) GetChats() []*ChatMetadata {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ChatMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FirstPrompt   string                 `protobuf:"bytes,3,opt,name=first_prompt,json=firstPrompt,proto3" json:"first_prompt,omitempty"`
	ChatTitle     string                 `protobuf:"bytes,4,opt,name=chat_title,json=chatTitle,proto3" json:"chat_title,omitempty"`
	LastUpdatedAt string                 `protobuf:"bytes,5,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	McpServerName string                 `protobuf:"bytes,7,opt,name=mcp_server_name,json=mcpServerName,proto3" json:"mcp_server_name,omitempty"`
	UserEmail     string                 `protobuf:"bytes,8,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMetadata) Reset() {
	*x = ChatMetadata{}
	mi := &file_bff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMetadata) ProtoMessage() {}

func (x *ChatMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMetadata.ProtoReflect.Descriptor instead.
func (*ChatMetadata) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{10}
}

func (x *ChatMetadata) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMetadata) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChatMetadata) GetFirstPrompt() string {
	if x != nil {
		return x.FirstPrompt
	}
	return ""
}

func (x *ChatMetadata) GetChatTitle() string {
	if x != nil {
		return x.ChatTitle
	}
	return ""
}

func (x *ChatMetadata) GetLastUpdatedAt() string {
	if x != nil {
		return x.LastUpdatedAt
	}
	return ""
}

func (x *ChatMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatMetadata) GetMcpServerName() string {
	if x != nil {
		return x.McpServerName
	}
	return ""
}

func (x *ChatMetadata) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetChatHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_bff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{11}
}

func (x *GetChatHistoryRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_bff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{12}
}

func (x *GetChatHistoryResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	RawToolResult string                 `protobuf:"bytes,4,opt,name=raw_tool_result,json=rawToolResult,proto3" json:"raw_tool_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_bff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{13}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChatMessage) GetRawToolResult() string {
	if x != nil {
		return x.RawToolResult
	}
	return ""
}

// LLM models messages
type GetLLMModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMModelsRequest) Reset() {
	*x = GetLLMModelsRequest{}
	mi := &file_bff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMModelsRequest) ProtoMessage() {}

func (x *GetLLMModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMModelsRequest.ProtoReflect.Descriptor instead.
func (*GetLLMModelsRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{14}
}

type GetLLMModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*LLMModel            `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLLMModelsResponse) Reset() {
	*x = GetLLMModelsResponse{}
	mi := &file_bff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLLMModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLLMModelsResponse) ProtoMessage() {}

func (x *GetLLMModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLLMModelsResponse.ProtoReflect.Descriptor instead.
func (*GetLLMModelsResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{15}
}

func (x *GetLLMModelsResponse) GetModels() []*LLMModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type LLMModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ModelId       int32                  `protobuf:"varint,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Object        string                 `protobuf:"bytes,3,opt,name=object,proto3" json:"object,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,4,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMModel) Reset() {
	*x = LLMModel{}
	mi := &file_bff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMModel) ProtoMessage() {}

func (x *LLMModel) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMModel.ProtoReflect.Descriptor instead.
func (*LLMModel) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{16}
}

func (x *LLMModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LLMModel) GetModelId() int32 {
	if x != nil {
		return x.ModelId
	}
	return 0
}

func (x *LLMModel) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *LLMModel) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

// MCP messages
type GetMcpInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpInfoRequest) Reset() {
	*x = GetMcpInfoRequest{}
	mi := &file_bff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpInfoRequest) ProtoMessage() {}

func (x *GetMcpInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMcpInfoRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{17}
}

type GetMcpInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpServers    []*MCPInfo             `protobuf:"bytes,1,rep,name=mcp_servers,json=mcpServers,proto3" json:"mcp_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpInfoResponse) Reset() {
	*x = GetMcpInfoResponse{}
	mi := &file_bff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpInfoResponse) ProtoMessage() {}

func (x *GetMcpInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMcpInfoResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{18}
}

func (x *GetMcpInfoResponse) GetMcpServers() []*MCPInfo {
	if x != nil {
		return x.McpServers
	}
	return nil
}

type GetMcpForUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpForUserRequest) Reset() {
	*x = GetMcpForUserRequest{}
	mi := &file_bff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpForUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpForUserRequest) ProtoMessage() {}

func (x *GetMcpForUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpForUserRequest.ProtoReflect.Descriptor instead.
func (*GetMcpForUserRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{19}
}

type GetMcpForUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpServers    []*MCPInfo             `protobuf:"bytes,1,rep,name=mcp_servers,json=mcpServers,proto3" json:"mcp_servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMcpForUserResponse) Reset() {
	*x = GetMcpForUserResponse{}
	mi := &file_bff_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMcpForUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMcpForUserResponse) ProtoMessage() {}

func (x *GetMcpForUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMcpForUserResponse.ProtoReflect.Descriptor instead.
func (*GetMcpForUserResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{20}
}

func (x *GetMcpForUserResponse) GetMcpServers() []*MCPInfo {
	if x != nil {
		return x.McpServers
	}
	return nil
}

type MCPInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerId         int32                  `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Transport        []string               `protobuf:"bytes,3,rep,name=transport,proto3" json:"transport,omitempty"`
	Tools            []string               `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	McpServerUrl     string                 `protobuf:"bytes,5,opt,name=mcp_server_url,json=mcpServerUrl,proto3" json:"mcp_server_url,omitempty"`
	Subscribe        bool                   `protobuf:"varint,6,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	RegisteredAt     string                 `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	ShortDescription string                 `protobuf:"bytes,8,opt,name=short_description,json=shortDescription,proto3" json:"short_description,omitempty"`
	LongDescription  string                 `protobuf:"bytes,9,opt,name=long_description,json=longDescription,proto3" json:"long_description,omitempty"`
	HelpUrl          string                 `protobuf:"bytes,10,opt,name=help_url,json=helpUrl,proto3" json:"help_url,omitempty"`
	Type             string                 `protobuf:"bytes,11,opt,name=type,proto3" json:"type,omitempty"`
	Details          []string               `protobuf:"bytes,12,rep,name=details,proto3" json:"details,omitempty"`
	Image            string                 `protobuf:"bytes,13,opt,name=image,proto3" json:"image,omitempty"`
	Suggestion       []string               `protobuf:"bytes,14,rep,name=suggestion,proto3" json:"suggestion,omitempty"`
	Timeout          int32                  `protobuf:"varint,15,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IsAvailable      bool                   `protobuf:"varint,16,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MCPInfo) Reset() {
	*x = MCPInfo{}
	mi := &file_bff_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPInfo) ProtoMessage() {}

func (x *MCPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPInfo.ProtoReflect.Descriptor instead.
func (*MCPInfo) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{21}
}

func (x *MCPInfo) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *MCPInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPInfo) GetTransport() []string {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *MCPInfo) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *MCPInfo) GetMcpServerUrl() string {
	if x != nil {
		return x.McpServerUrl
	}
	return ""
}

func (x *MCPInfo) GetSubscribe() bool {
	if x != nil {
		return x.Subscribe
	}
	return false
}

func (x *MCPInfo) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *MCPInfo) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *MCPInfo) GetLongDescription() string {
	if x != nil {
		return x.LongDescription
	}
	return ""
}

func (x *MCPInfo) GetHelpUrl() string {
	if x != nil {
		return x.HelpUrl
	}
	return ""
}

func (x *MCPInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MCPInfo) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *MCPInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MCPInfo) GetSuggestion() []string {
	if x != nil {
		return x.Suggestion
	}
	return nil
}

func (x *MCPInfo) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *MCPInfo) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type SelectMcpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	McpInfo       *MCPInfo               `protobuf:"bytes,1,opt,name=mcp_info,json=mcpInfo,proto3" json:"mcp_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectMcpRequest) Reset() {
	*x = SelectMcpRequest{}
	mi := &file_bff_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectMcpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMcpRequest) ProtoMessage() {}

func (x *SelectMcpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMcpRequest.ProtoReflect.Descriptor instead.
func (*SelectMcpRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{22}
}

func (x *SelectMcpRequest) GetMcpInfo() *MCPInfo {
	if x != nil {
		return x.McpInfo
	}
	return nil
}

type SelectMcpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectMcpResponse) Reset() {
	*x = SelectMcpResponse{}
	mi := &file_bff_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectMcpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectMcpResponse) ProtoMessage() {}

func (x *SelectMcpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectMcpResponse.ProtoReflect.Descriptor instead.
func (*SelectMcpResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{23}
}

func (x *SelectMcpResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SelectMcpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// User settings messages
type GetUserSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsRequest) Reset() {
	*x = GetUserSettingsRequest{}
	mi := &file_bff_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsRequest) ProtoMessage() {}

func (x *GetUserSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetUserSettingsRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{24}
}

type GetUserSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LlmModels     []*LLMModel            `protobuf:"bytes,1,rep,name=llm_models,json=llmModels,proto3" json:"llm_models,omitempty"`
	McpInfo       []*MCPInfo             `protobuf:"bytes,2,rep,name=mcp_info,json=mcpInfo,proto3" json:"mcp_info,omitempty"`
	McpForUser    []*MCPInfo             `protobuf:"bytes,3,rep,name=mcp_for_user,json=mcpForUser,proto3" json:"mcp_for_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsResponse) Reset() {
	*x = GetUserSettingsResponse{}
	mi := &file_bff_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsResponse) ProtoMessage() {}

func (x *GetUserSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetUserSettingsResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserSettingsResponse) GetLlmModels() []*LLMModel {
	if x != nil {
		return x.LlmModels
	}
	return nil
}

func (x *GetUserSettingsResponse) GetMcpInfo() []*MCPInfo {
	if x != nil {
		return x.McpInfo
	}
	return nil
}

func (x *GetUserSettingsResponse) GetMcpForUser() []*MCPInfo {
	if x != nil {
		return x.McpForUser
	}
	return nil
}

// Rate limit messages
type QueryRateLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRateLimitRequest) Reset() {
	*x = QueryRateLimitRequest{}
	mi := &file_bff_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRateLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRateLimitRequest) ProtoMessage() {}

func (x *QueryRateLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRateLimitRequest.ProtoReflect.Descriptor instead.
func (*QueryRateLimitRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{26}
}

type QueryRateLimitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining      int32                  `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	ResetAt        int64                  `protobuf:"varint,3,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	UserStats      *UserLimitStats        `protobuf:"bytes,5,opt,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	TokenUsage     *TokenUsage            `protobuf:"bytes,6,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"`
	CircuitBreaker *CircuitBreakerStats   `protobuf:"bytes,7,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryRateLimitResponse) Reset() {
	*x = QueryRateLimitResponse{}
	mi := &file_bff_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRateLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRateLimitResponse) ProtoMessage() {}

func (x *QueryRateLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRateLimitResponse.ProtoReflect.Descriptor instead.
func (*QueryRateLimitResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{27}
}

func (x *QueryRateLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *QueryRateLimitResponse) GetRemaining() int32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *QueryRateLimitResponse) GetResetAt() int64 {
	if x != nil {
		return x.ResetAt
	}
	return 0
}

func (x *QueryRateLimitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryRateLimitResponse) GetUserStats() *UserLimitStats {
	if x != nil {
		return x.UserStats
	}
	return nil
}

func (x *QueryRateLimitResponse) GetTokenUsage() *TokenUsage {
	if x != nil {
		return x.TokenUsage
	}
	return nil
}

func (x *QueryRateLimitResponse) GetCircuitBreaker() *CircuitBreakerStats {
	if x != nil {
		return x.CircuitBreaker
	}
	return nil
}

type UserLimitStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlanType          string                 `protobuf:"bytes,1,opt,name=plan_type,json=planType,proto3" json:"plan_type,omitempty"`
	HourlyPercentage  float64                `protobuf:"fixed64,2,opt,name=hourly_percentage,json=hourlyPercentage,proto3" json:"hourly_percentage,omitempty"`
	DailyPercentage   float64                `protobuf:"fixed64,3,opt,name=daily_percentage,json=dailyPercentage,proto3" json:"daily_percentage,omitempty"`
	MonthlyPercentage float64                `protobuf:"fixed64,4,opt,name=monthly_percentage,json=monthlyPercentage,proto3" json:"monthly_percentage,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserLimitStats) Reset() {
	*x = UserLimitStats{}
	mi := &file_bff_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLimitStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLimitStats) ProtoMessage() {}

func (x *UserLimitStats) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLimitStats.ProtoReflect.Descriptor instead.
func (*UserLimitStats) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{28}
}

func (x *UserLimitStats) GetPlanType() string {
	if x != nil {
		return x.PlanType
	}
	return ""
}

func (x *UserLimitStats) GetHourlyPercentage() float64 {
	if x != nil {
		return x.HourlyPercentage
	}
	return 0
}

func (x *UserLimitStats) GetDailyPercentage() float64 {
	if x != nil {
		return x.DailyPercentage
	}
	return 0
}

func (x *UserLimitStats) GetMonthlyPercentage() float64 {
	if x != nil {
		return x.MonthlyPercentage
	}
	return 0
}

type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int64                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int64                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_bff_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{29}
}

func (x *TokenUsage) GetInputTokens() int64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() int64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type CircuitBreakerStats struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestsPerMinute int32                  `protobuf:"varint,1,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	TokensPerMinute   int32                  `protobuf:"varint,2,opt,name=tokens_per_minute,json=tokensPerMinute,proto3" json:"tokens_per_minute,omitempty"`
	ViolationCount    int32                  `protobuf:"varint,3,opt,name=violation_count,json=violationCount,proto3" json:"violation_count,omitempty"`
	LastViolation     string                 `protobuf:"bytes,4,opt,name=last_violation,json=lastViolation,proto3" json:"last_violation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CircuitBreakerStats) Reset() {
	*x = CircuitBreakerStats{}
	mi := &file_bff_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitBreakerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitBreakerStats) ProtoMessage() {}

func (x *CircuitBreakerStats) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitBreakerStats.ProtoReflect.Descriptor instead.
func (*CircuitBreakerStats) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{30}
}

func (x *CircuitBreakerStats) GetRequestsPerMinute() int32 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

func (x *CircuitBreakerStats) GetTokensPerMinute() int32 {
	if x != nil {
		return x.TokensPerMinute
	}
	return 0
}

func (x *CircuitBreakerStats) GetViolationCount() int32 {
	if x != nil {
		return x.ViolationCount
	}
	return 0
}

func (x *CircuitBreakerStats) GetLastViolation() string {
	if x != nil {
		return x.LastViolation
	}
	return ""
}

// Chat context messages
type GetChatContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatContextRequest) Reset() {
	*x = GetChatContextRequest{}
	mi := &file_bff_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatContextRequest) ProtoMessage() {}

func (x *GetChatContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatContextRequest.ProtoReflect.Descriptor instead.
func (*GetChatContextRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{31}
}

func (x *GetChatContextRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type GetChatContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChatMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatContextResponse) Reset() {
	*x = GetChatContextResponse{}
	mi := &file_bff_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatContextResponse) ProtoMessage() {}

func (x *GetChatContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatContextResponse.ProtoReflect.Descriptor instead.
func (*GetChatContextResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{32}
}

func (x *GetChatContextResponse) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Stripe subscription messages
type GetStripeSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStripeSubscriptionRequest) Reset() {
	*x = GetStripeSubscriptionRequest{}
	mi := &file_bff_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripeSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripeSubscriptionRequest) ProtoMessage() {}

func (x *GetStripeSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripeSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetStripeSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{33}
}

type GetStripeSubscriptionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HasSubscription    bool                   `protobuf:"varint,1,opt,name=has_subscription,json=hasSubscription,proto3" json:"has_subscription,omitempty"`
	PlanName           string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	SubscriptionStatus string                 `protobuf:"bytes,3,opt,name=subscription_status,json=subscriptionStatus,proto3" json:"subscription_status,omitempty"`
	ExpirationDate     string                 `protobuf:"bytes,4,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	CustomerId         string                 `protobuf:"bytes,5,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	SubscriptionId     string                 `protobuf:"bytes,6,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	DailyTokenLimit    int64                  `protobuf:"varint,7,opt,name=daily_token_limit,json=dailyTokenLimit,proto3" json:"daily_token_limit,omitempty"`
	MonthlyTokenLimit  int64                  `protobuf:"varint,8,opt,name=monthly_token_limit,json=monthlyTokenLimit,proto3" json:"monthly_token_limit,omitempty"`
	Error              string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetStripeSubscriptionResponse) Reset() {
	*x = GetStripeSubscriptionResponse{}
	mi := &file_bff_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripeSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripeSubscriptionResponse) ProtoMessage() {}

func (x *GetStripeSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripeSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetStripeSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{34}
}

func (x *GetStripeSubscriptionResponse) GetHasSubscription() bool {
	if x != nil {
		return x.HasSubscription
	}
	return false
}

func (x *GetStripeSubscriptionResponse) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *GetStripeSubscriptionResponse) GetSubscriptionStatus() string {
	if x != nil {
		return x.SubscriptionStatus
	}
	return ""
}

func (x *GetStripeSubscriptionResponse) GetExpirationDate() string {
	if x != nil {
		return x.ExpirationDate
	}
	return ""
}

func (x *GetStripeSubscriptionResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetStripeSubscriptionResponse) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *GetStripeSubscriptionResponse) GetDailyTokenLimit() int64 {
	if x != nil {
		return x.DailyTokenLimit
	}
	return 0
}

func (x *GetStripeSubscriptionResponse) GetMonthlyTokenLimit() int64 {
	if x != nil {
		return x.MonthlyTokenLimit
	}
	return 0
}

func (x *GetStripeSubscriptionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Stripe plans messages
type GetStripePlansRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStripePlansRequest) Reset() {
	*x = GetStripePlansRequest{}
	mi := &file_bff_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripePlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripePlansRequest) ProtoMessage() {}

func (x *GetStripePlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripePlansRequest.ProtoReflect.Descriptor instead.
func (*GetStripePlansRequest) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{35}
}

type GetStripePlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plans         []*StripePlan          `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStripePlansResponse) Reset() {
	*x = GetStripePlansResponse{}
	mi := &file_bff_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStripePlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStripePlansResponse) ProtoMessage() {}

func (x *GetStripePlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStripePlansResponse.ProtoReflect.Descriptor instead.
func (*GetStripePlansResponse) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{36}
}

func (x *GetStripePlansResponse) GetPlans() []*StripePlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *GetStripePlansResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StripePlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlanId            string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PriceCents        int64                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	BillingPeriod     string                 `protobuf:"bytes,5,opt,name=billing_period,json=billingPeriod,proto3" json:"billing_period,omitempty"`
	Features          []string               `protobuf:"bytes,6,rep,name=features,proto3" json:"features,omitempty"`
	DailyTokenLimit   int64                  `protobuf:"varint,7,opt,name=daily_token_limit,json=dailyTokenLimit,proto3" json:"daily_token_limit,omitempty"`
	MonthlyTokenLimit int64                  `protobuf:"varint,8,opt,name=monthly_token_limit,json=monthlyTokenLimit,proto3" json:"monthly_token_limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StripePlan) Reset() {
	*x = StripePlan{}
	mi := &file_bff_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripePlan) ProtoMessage() {}

func (x *StripePlan) ProtoReflect() protoreflect.Message {
	mi := &file_bff_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripePlan.ProtoReflect.Descriptor instead.
func (*StripePlan) Descriptor() ([]byte, []int) {
	return file_bff_proto_rawDescGZIP(), []int{37}
}

func (x *StripePlan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *StripePlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StripePlan) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StripePlan) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *StripePlan) GetBillingPeriod() string {
	if x != nil {
		return x.BillingPeriod
	}
	return ""
}

func (x *StripePlan) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *StripePlan) GetDailyTokenLimit() int64 {
	if x != nil {
		return x.DailyTokenLimit
	}
	return 0
}

func (x *StripePlan) GetMonthlyTokenLimit() int64 {
	if x != nil {
		return x.MonthlyTokenLimit
	}
	return 0
}

var File_bff_proto protoreflect.FileDescriptor

const file_bff_proto_rawDesc = "" +
	"\n" +
	"\tbff.proto\x12\x06bff.v1\"\x14\n" +
	"\x12GetUserInfoRequest\"\xe7\x01\n" +
	"\x13GetUserInfoResponse\x12\x10\n" +
	"\x03sub\x18\x01 \x01(\tR\x03sub\x12%\n" +
	"\x0eemail_verified\x18\x02 \x01(\bR\remailVerified\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12-\n" +
	"\x12preferred_username\x18\x04 \x01(\tR\x11preferredUsername\x12\x1d\n" +
	"\n" +
	"given_name\x18\x05 \x01(\tR\tgivenName\x12\x1f\n" +
	"\vfamily_name\x18\x06 \x01(\tR\n" +
	"familyName\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\"\xdf\x01\n" +
	"\vChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12&\n" +
	"\x0fmcp_server_name\x18\x04 \x01(\tR\rmcpServerName\x12\x1e\n" +
	"\vis_new_chat\x18\x05 \x01(\bR\tisNewChat\x12\x19\n" +
	"\bfile_url\x18\x06 \x01(\tR\afileUrl\x12&\n" +
	"\x0fraw_tool_result\x18\a \x01(\tR\rrawToolResult\"c\n" +
	"\tChatEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"*\n" +
	"\x0fStopChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\",\n" +
	"\x10StopChatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x14GenerateTitleRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\"V\n" +
	"\x15GenerateTitleResponse\x12'\n" +
	"\x0fgenerated_title\x18\x01 \x01(\tR\x0egeneratedTitle\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x13\n" +
	"\x11GetChatIdsRequest\"@\n" +
	"\x12GetChatIdsResponse\x12*\n" +
	"\x05chats\x18\x01 \x03(\v2\x14.bff.v1.ChatMetadataR\x05chats\"\x8d\x02\n" +
	"\fChatMetadata\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\tR\tcreatedAt\x12!\n" +
	"\ffirst_prompt\x18\x03 \x01(\tR\vfirstPrompt\x12\x1d\n" +
	"\n" +
	"chat_title\x18\x04 \x01(\tR\tchatTitle\x12&\n" +
	"\x0flast_updated_at\x18\x05 \x01(\tR\rlastUpdatedAt\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\x12&\n" +
	"\x0fmcp_server_name\x18\a \x01(\tR\rmcpServerName\x12\x1d\n" +
	"\n" +
	"user_email\x18\b \x01(\tR\tuserEmail\"0\n" +
	"\x15GetChatHistoryRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"I\n" +
	"\x16GetChatHistoryResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.bff.v1.ChatMessageR\bmessages\"\x82\x01\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12&\n" +
	"\x0fraw_tool_result\x18\x04 \x01(\tR\rrawToolResult\"\x15\n" +
	"\x13GetLLMModelsRequest\"@\n" +
	"\x14GetLLMModelsResponse\x12(\n" +
	"\x06models\x18\x01 \x03(\v2\x10.bff.v1.LLMModelR\x06models\"l\n" +
	"\bLLMModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\x05R\amodelId\x12\x16\n" +
	"\x06object\x18\x03 \x01(\tR\x06object\x12\x19\n" +
	"\bowned_by\x18\x04 \x01(\tR\aownedBy\"\x13\n" +
	"\x11GetMcpInfoRequest\"F\n" +
	"\x12GetMcpInfoResponse\x120\n" +
	"\vmcp_servers\x18\x01 \x03(\v2\x0f.bff.v1.MCPInfoR\n" +
	"mcpServers\"\x16\n" +
	"\x14GetMcpForUserRequest\"I\n" +
	"\x15GetMcpForUserResponse\x120\n" +
	"\vmcp_servers\x18\x01 \x03(\v2\x0f.bff.v1.MCPInfoR\n" +
	"mcpServers\"\xeb\x03\n" +
	"\aMCPInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\ttransport\x18\x03 \x03(\tR\ttransport\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12$\n" +
	"\x0emcp_server_url\x18\x05 \x01(\tR\fmcpServerUrl\x12\x1c\n" +
	"\tsubscribe\x18\x06 \x01(\bR\tsubscribe\x12#\n" +
	"\rregistered_at\x18\a \x01(\tR\fregisteredAt\x12+\n" +
	"\x11short_description\x18\b \x01(\tR\x10shortDescription\x12)\n" +
	"\x10long_description\x18\t \x01(\tR\x0flongDescription\x12\x19\n" +
	"\bhelp_url\x18\n" +
	" \x01(\tR\ahelpUrl\x12\x12\n" +
	"\x04type\x18\v \x01(\tR\x04type\x12\x18\n" +
	"\adetails\x18\f \x03(\tR\adetails\x12\x14\n" +
	"\x05image\x18\r \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x0e \x03(\tR\n" +
	"suggestion\x12\x18\n" +
	"\atimeout\x18\x0f \x01(\x05R\atimeout\x12!\n" +
	"\fis_available\x18\x10 \x01(\bR\visAvailable\">\n" +
	"\x10SelectMcpRequest\x12*\n" +
	"\bmcp_info\x18\x01 \x01(\v2\x0f.bff.v1.MCPInfoR\amcpInfo\"C\n" +
	"\x11SelectMcpResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x18\n" +
	"\x16GetUserSettingsRequest\"\xa9\x01\n" +
	"\x17GetUserSettingsResponse\x12/\n" +
	"\n" +
	"llm_models\x18\x01 \x03(\v2\x10.bff.v1.LLMModelR\tllmModels\x12*\n" +
	"\bmcp_info\x18\x02 \x03(\v2\x0f.bff.v1.MCPInfoR\amcpInfo\x121\n" +
	"\fmcp_for_user\x18\x03 \x03(\v2\x0f.bff.v1.MCPInfoR\n" +
	"mcpForUser\"\x17\n" +
	"\x15QueryRateLimitRequest\"\xb3\x02\n" +
	"\x16QueryRateLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x05R\tremaining\x12\x19\n" +
	"\breset_at\x18\x03 \x01(\x03R\aresetAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x125\n" +
	"\n" +
	"user_stats\x18\x05 \x01(\v2\x16.bff.v1.UserLimitStatsR\tuserStats\x123\n" +
	"\vtoken_usage\x18\x06 \x01(\v2\x12.bff.v1.TokenUsageR\n" +
	"tokenUsage\x12D\n" +
	"\x0fcircuit_breaker\x18\a \x01(\v2\x1b.bff.v1.CircuitBreakerStatsR\x0ecircuitBreaker\"\xb4\x01\n" +
	"\x0eUserLimitStats\x12\x1b\n" +
	"\tplan_type\x18\x01 \x01(\tR\bplanType\x12+\n" +
	"\x11hourly_percentage\x18\x02 \x01(\x01R\x10hourlyPercentage\x12)\n" +
	"\x10daily_percentage\x18\x03 \x01(\x01R\x0fdailyPercentage\x12-\n" +
	"\x12monthly_percentage\x18\x04 \x01(\x01R\x11monthlyPercentage\"w\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x03R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x03R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\"\xc1\x01\n" +
	"\x13CircuitBreakerStats\x12.\n" +
	"\x13requests_per_minute\x18\x01 \x01(\x05R\x11requestsPerMinute\x12*\n" +
	"\x11tokens_per_minute\x18\x02 \x01(\x05R\x0ftokensPerMinute\x12'\n" +
	"\x0fviolation_count\x18\x03 \x01(\x05R\x0eviolationCount\x12%\n" +
	"\x0elast_violation\x18\x04 \x01(\tR\rlastViolation\"0\n" +
	"\x15GetChatContextRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\tR\x06chatId\"I\n" +
	"\x16GetChatContextResponse\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.bff.v1.ChatMessageR\bmessages\"\x1e\n" +
	"\x1cGetStripeSubscriptionRequest\"\xfd\x02\n" +
	"\x1dGetStripeSubscriptionResponse\x12)\n" +
	"\x10has_subscription\x18\x01 \x01(\bR\x0fhasSubscription\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12/\n" +
	"\x13subscription_status\x18\x03 \x01(\tR\x12subscriptionStatus\x12'\n" +
	"\x0fexpiration_date\x18\x04 \x01(\tR\x0eexpirationDate\x12\x1f\n" +
	"\vcustomer_id\x18\x05 \x01(\tR\n" +
	"customerId\x12'\n" +
	"\x0fsubscription_id\x18\x06 \x01(\tR\x0esubscriptionId\x12*\n" +
	"\x11daily_token_limit\x18\a \x01(\x03R\x0fdailyTokenLimit\x12.\n" +
	"\x13monthly_token_limit\x18\b \x01(\x03R\x11monthlyTokenLimit\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\x17\n" +
	"\x15GetStripePlansRequest\"X\n" +
	"\x16GetStripePlansResponse\x12(\n" +
	"\x05plans\x18\x01 \x03(\v2\x12.bff.v1.StripePlanR\x05plans\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x9b\x02\n" +
	"\n" +
	"StripePlan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x03R\n" +
	"priceCents\x12%\n" +
	"\x0ebilling_period\x18\x05 \x01(\tR\rbillingPeriod\x12\x1a\n" +
	"\bfeatures\x18\x06 \x03(\tR\bfeatures\x12*\n" +
	"\x11daily_token_limit\x18\a \x01(\x03R\x0fdailyTokenLimit\x12.\n" +
	"\x13monthly_token_limit\x18\b \x01(\x03R\x11monthlyTokenLimit2\xf6\b\n" +
	"\n" +
	"BFFService\x12F\n" +
	"\vGetUserInfo\x12\x1a.bff.v1.GetUserInfoRequest\x1a\x1b.bff.v1.GetUserInfoResponse\x120\n" +
	"\x04Chat\x12\x13.bff.v1.ChatRequest\x1a\x11.bff.v1.ChatEvent0\x01\x12=\n" +
	"\bStopChat\x12\x17.bff.v1.StopChatRequest\x1a\x18.bff.v1.StopChatResponse\x12L\n" +
	"\rGenerateTitle\x12\x1c.bff.v1.GenerateTitleRequest\x1a\x1d.bff.v1.GenerateTitleResponse\x12C\n" +
	"\n" +
	"GetChatIds\x12\x19.bff.v1.GetChatIdsRequest\x1a\x1a.bff.v1.GetChatIdsResponse\x12O\n" +
	"\x0eGetChatHistory\x12\x1d.bff.v1.GetChatHistoryRequest\x1a\x1e.bff.v1.GetChatHistoryResponse\x12O\n" +
	"\x0eGetChatContext\x12\x1d.bff.v1.GetChatContextRequest\x1a\x1e.bff.v1.GetChatContextResponse\x12I\n" +
	"\fGetLLMModels\x12\x1b.bff.v1.GetLLMModelsRequest\x1a\x1c.bff.v1.GetLLMModelsResponse\x12C\n" +
	"\n" +
	"GetMcpInfo\x12\x19.bff.v1.GetMcpInfoRequest\x1a\x1a.bff.v1.GetMcpInfoResponse\x12L\n" +
	"\rGetMcpForUser\x12\x1c.bff.v1.GetMcpForUserRequest\x1a\x1d.bff.v1.GetMcpForUserResponse\x12@\n" +
	"\tSelectMcp\x12\x18.bff.v1.SelectMcpRequest\x1a\x19.bff.v1.SelectMcpResponse\x12R\n" +
	"\x0fGetUserSettings\x12\x1e.bff.v1.GetUserSettingsRequest\x1a\x1f.bff.v1.GetUserSettingsResponse\x12O\n" +
	"\x0eQueryRateLimit\x12\x1d.bff.v1.QueryRateLimitRequest\x1a\x1e.bff.v1.QueryRateLimitResponse\x12d\n" +
	"\x15GetStripeSubscription\x12$.bff.v1.GetStripeSubscriptionRequest\x1a%.bff.v1.GetStripeSubscriptionResponse\x12O\n" +
	"\x0eGetStripePlans\x12\x1d.bff.v1.GetStripePlansRequest\x1a\x1e.bff.v1.GetStripePlansResponseB,Z*github.com/bluefunda/cai-bff/api/proto/bffb\x06proto3"

var (
	file_bff_proto_rawDescOnce sync.Once
	file_bff_proto_rawDescData []byte
)

func file_bff_proto_rawDescGZIP() []byte {
	file_bff_proto_rawDescOnce.Do(func() {
		file_bff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bff_proto_rawDesc), len(file_bff_proto_rawDesc)))
	})
	return file_bff_proto_rawDescData
}

var file_bff_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_bff_proto_goTypes = []any{
	(*GetUserInfoRequest)(nil),            // 0: bff.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),           // 1: bff.v1.GetUserInfoResponse
	(*ChatRequest)(nil),                   // 2: bff.v1.ChatRequest
	(*ChatEvent)(nil),                     // 3: bff.v1.ChatEvent
	(*StopChatRequest)(nil),               // 4: bff.v1.StopChatRequest
	(*StopChatResponse)(nil),              // 5: bff.v1.StopChatResponse
	(*GenerateTitleRequest)(nil),          // 6: bff.v1.GenerateTitleRequest
	(*GenerateTitleResponse)(nil),         // 7: bff.v1.GenerateTitleResponse
	(*GetChatIdsRequest)(nil),             // 8: bff.v1.GetChatIdsRequest
	(*GetChatIdsResponse)(nil),            // 9: bff.v1.GetChatIdsResponse
	(*ChatMetadata)(nil),                  // 10: bff.v1.ChatMetadata
	(*GetChatHistoryRequest)(nil),         // 11: bff.v1.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil),        // 12: bff.v1.GetChatHistoryResponse
	(*ChatMessage)(nil),                   // 13: bff.v1.ChatMessage
	(*GetLLMModelsRequest)(nil),           // 14: bff.v1.GetLLMModelsRequest
	(*GetLLMModelsResponse)(nil),          // 15: bff.v1.GetLLMModelsResponse
	(*LLMModel)(nil),                      // 16: bff.v1.LLMModel
	(*GetMcpInfoRequest)(nil),             // 17: bff.v1.GetMcpInfoRequest
	(*GetMcpInfoResponse)(nil),            // 18: bff.v1.GetMcpInfoResponse
	(*GetMcpForUserRequest)(nil),          // 19: bff.v1.GetMcpForUserRequest
	(*GetMcpForUserResponse)(nil),         // 20: bff.v1.GetMcpForUserResponse
	(*MCPInfo)(nil),                       // 21: bff.v1.MCPInfo
	(*SelectMcpRequest)(nil),              // 22: bff.v1.SelectMcpRequest
	(*SelectMcpResponse)(nil),             // 23: bff.v1.SelectMcpResponse
	(*GetUserSettingsRequest)(nil),        // 24: bff.v1.GetUserSettingsRequest
	(*GetUserSettingsResponse)(nil),       // 25: bff.v1.GetUserSettingsResponse
	(*QueryRateLimitRequest)(nil),         // 26: bff.v1.QueryRateLimitRequest
	(*QueryRateLimitResponse)(nil),        // 27: bff.v1.QueryRateLimitResponse
	(*UserLimitStats)(nil),                // 28: bff.v1.UserLimitStats
	(*TokenUsage)(nil),                    // 29: bff.v1.TokenUsage
	(*CircuitBreakerStats)(nil),           // 30: bff.v1.CircuitBreakerStats
	(*GetChatContextRequest)(nil),         // 31: bff.v1.GetChatContextRequest
	(*GetChatContextResponse)(nil),        // 32: bff.v1.GetChatContextResponse
	(*GetStripeSubscriptionRequest)(nil),  // 33: bff.v1.GetStripeSubscriptionRequest
	(*GetStripeSubscriptionResponse)(nil), // 34: bff.v1.GetStripeSubscriptionResponse
	(*GetStripePlansRequest)(nil),         // 35: bff.v1.GetStripePlansRequest
	(*GetStripePlansResponse)(nil),        // 36: bff.v1.GetStripePlansResponse
	(*StripePlan)(nil),                    // 37: bff.v1.StripePlan
}
var file_bff_proto_depIdxs = []int32{
	10, // 0: bff.v1.GetChatIdsResponse.chats:type_name -> bff.v1.ChatMetadata
	13, // 1: bff.v1.GetChatHistoryResponse.messages:type_name -> bff.v1.ChatMessage
	16, // 2: bff.v1.GetLLMModelsResponse.models:type_name -> bff.v1.LLMModel
	21, // 3: bff.v1.GetMcpInfoResponse.mcp_servers:type_name -> bff.v1.MCPInfo
	21, // 4: bff.v1.GetMcpForUserResponse.mcp_servers:type_name -> bff.v1.MCPInfo
	21, // 5: bff.v1.SelectMcpRequest.mcp_info:type_name -> bff.v1.MCPInfo
	16, // 6: bff.v1.GetUserSettingsResponse.llm_models:type_name -> bff.v1.LLMModel
	21, // 7: bff.v1.GetUserSettingsResponse.mcp_info:type_name -> bff.v1.MCPInfo
	21, // 8: bff.v1.GetUserSettingsResponse.mcp_for_user:type_name -> bff.v1.MCPInfo
	28, // 9: bff.v1.QueryRateLimitResponse.user_stats:type_name -> bff.v1.UserLimitStats
	29, // 10: bff.v1.QueryRateLimitResponse.token_usage:type_name -> bff.v1.TokenUsage
	30, // 11: bff.v1.QueryRateLimitResponse.circuit_breaker:type_name -> bff.v1.CircuitBreakerStats
	13, // 12: bff.v1.GetChatContextResponse.messages:type_name -> bff.v1.ChatMessage
	37, // 13: bff.v1.GetStripePlansResponse.plans:type_name -> bff.v1.StripePlan
	0,  // 14: bff.v1.BFFService.GetUserInfo:input_type -> bff.v1.GetUserInfoRequest
	2,  // 15: bff.v1.BFFService.Chat:input_type -> bff.v1.ChatRequest
	4,  // 16: bff.v1.BFFService.StopChat:input_type -> bff.v1.StopChatRequest
	6,  // 17: bff.v1.BFFService.GenerateTitle:input_type -> bff.v1.GenerateTitleRequest
	8,  // 18: bff.v1.BFFService.GetChatIds:input_type -> bff.v1.GetChatIdsRequest
	11, // 19: bff.v1.BFFService.GetChatHistory:input_type -> bff.v1.GetChatHistoryRequest
	31, // 20: bff.v1.BFFService.GetChatContext:input_type -> bff.v1.GetChatContextRequest
	14, // 21: bff.v1.BFFService.GetLLMModels:input_type -> bff.v1.GetLLMModelsRequest
	17, // 22: bff.v1.BFFService.GetMcpInfo:input_type -> bff.v1.GetMcpInfoRequest
	19, // 23: bff.v1.BFFService.GetMcpForUser:input_type -> bff.v1.GetMcpForUserRequest
	22, // 24: bff.v1.BFFService.SelectMcp:input_type -> bff.v1.SelectMcpRequest
	24, // 25: bff.v1.BFFService.GetUserSettings:input_type -> bff.v1.GetUserSettingsRequest
	26, // 26: bff.v1.BFFService.QueryRateLimit:input_type -> bff.v1.QueryRateLimitRequest
	33, // 27: bff.v1.BFFService.GetStripeSubscription:input_type -> bff.v1.GetStripeSubscriptionRequest
	35, // 28: bff.v1.BFFService.GetStripePlans:input_type -> bff.v1.GetStripePlansRequest
	1,  // 29: bff.v1.BFFService.GetUserInfo:output_type -> bff.v1.GetUserInfoResponse
	3,  // 30: bff.v1.BFFService.Chat:output_type -> bff.v1.ChatEvent
	5,  // 31: bff.v1.BFFService.StopChat:output_type -> bff.v1.StopChatResponse
	7,  // 32: bff.v1.BFFService.GenerateTitle:output_type -> bff.v1.GenerateTitleResponse
	9,  // 33: bff.v1.BFFService.GetChatIds:output_type -> bff.v1.GetChatIdsResponse
	12, // 34: bff.v1.BFFService.GetChatHistory:output_type -> bff.v1.GetChatHistoryResponse
	32, // 35: bff.v1.BFFService.GetChatContext:output_type -> bff.v1.GetChatContextResponse
	15, // 36: bff.v1.BFFService.GetLLMModels:output_type -> bff.v1.GetLLMModelsResponse
	18, // 37: bff.v1.BFFService.GetMcpInfo:output_type -> bff.v1.GetMcpInfoResponse
	20, // 38: bff.v1.BFFService.GetMcpForUser:output_type -> bff.v1.GetMcpForUserResponse
	23, // 39: bff.v1.BFFService.SelectMcp:output_type -> bff.v1.SelectMcpResponse
	25, // 40: bff.v1.BFFService.GetUserSettings:output_type -> bff.v1.GetUserSettingsResponse
	27, // 41: bff.v1.BFFService.QueryRateLimit:output_type -> bff.v1.QueryRateLimitResponse
	34, // 42: bff.v1.BFFService.GetStripeSubscription:output_type -> bff.v1.GetStripeSubscriptionResponse
	36, // 43: bff.v1.BFFService.GetStripePlans:output_type -> bff.v1.GetStripePlansResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_bff_proto_init() }
func file_bff_proto_init() {
	if File_bff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bff_proto_rawDesc), len(file_bff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bff_proto_goTypes,
		DependencyIndexes: file_bff_proto_depIdxs,
		MessageInfos:      file_bff_proto_msgTypes,
	}.Build()
	File_bff_proto = out.File
	file_bff_proto_goTypes = nil
	file_bff_proto_depIdxs = nil
}
