// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: bff.proto

package bff

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BFFService_GetUserInfo_FullMethodName           = "/bff.v1.BFFService/GetUserInfo"
	BFFService_Chat_FullMethodName                  = "/bff.v1.BFFService/Chat"
	BFFService_StopChat_FullMethodName              = "/bff.v1.BFFService/StopChat"
	BFFService_GenerateTitle_FullMethodName         = "/bff.v1.BFFService/GenerateTitle"
	BFFService_GetChatIds_FullMethodName            = "/bff.v1.BFFService/GetChatIds"
	BFFService_GetChatHistory_FullMethodName        = "/bff.v1.BFFService/GetChatHistory"
	BFFService_GetChatContext_FullMethodName        = "/bff.v1.BFFService/GetChatContext"
	BFFService_GetLLMModels_FullMethodName          = "/bff.v1.BFFService/GetLLMModels"
	BFFService_GetMcpInfo_FullMethodName            = "/bff.v1.BFFService/GetMcpInfo"
	BFFService_GetMcpForUser_FullMethodName         = "/bff.v1.BFFService/GetMcpForUser"
	BFFService_SelectMcp_FullMethodName             = "/bff.v1.BFFService/SelectMcp"
	BFFService_GetUserSettings_FullMethodName       = "/bff.v1.BFFService/GetUserSettings"
	BFFService_QueryRateLimit_FullMethodName        = "/bff.v1.BFFService/QueryRateLimit"
	BFFService_GetStripeSubscription_FullMethodName = "/bff.v1.BFFService/GetStripeSubscription"
	BFFService_GetStripePlans_FullMethodName        = "/bff.v1.BFFService/GetStripePlans"
)

// BFFServiceClient is the client API for BFFService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BFFService provides backend-for-frontend operations
type BFFServiceClient interface {
	// User info
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// Chat operations (streaming for CLI)
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error)
	StopChat(ctx context.Context, in *StopChatRequest, opts ...grpc.CallOption) (*StopChatResponse, error)
	GenerateTitle(ctx context.Context, in *GenerateTitleRequest, opts ...grpc.CallOption) (*GenerateTitleResponse, error)
	// Query operations
	GetChatIds(ctx context.Context, in *GetChatIdsRequest, opts ...grpc.CallOption) (*GetChatIdsResponse, error)
	GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error)
	GetChatContext(ctx context.Context, in *GetChatContextRequest, opts ...grpc.CallOption) (*GetChatContextResponse, error)
	GetLLMModels(ctx context.Context, in *GetLLMModelsRequest, opts ...grpc.CallOption) (*GetLLMModelsResponse, error)
	GetMcpInfo(ctx context.Context, in *GetMcpInfoRequest, opts ...grpc.CallOption) (*GetMcpInfoResponse, error)
	GetMcpForUser(ctx context.Context, in *GetMcpForUserRequest, opts ...grpc.CallOption) (*GetMcpForUserResponse, error)
	SelectMcp(ctx context.Context, in *SelectMcpRequest, opts ...grpc.CallOption) (*SelectMcpResponse, error)
	GetUserSettings(ctx context.Context, in *GetUserSettingsRequest, opts ...grpc.CallOption) (*GetUserSettingsResponse, error)
	QueryRateLimit(ctx context.Context, in *QueryRateLimitRequest, opts ...grpc.CallOption) (*QueryRateLimitResponse, error)
	// Stripe/Billing operations
	GetStripeSubscription(ctx context.Context, in *GetStripeSubscriptionRequest, opts ...grpc.CallOption) (*GetStripeSubscriptionResponse, error)
	GetStripePlans(ctx context.Context, in *GetStripePlansRequest, opts ...grpc.CallOption) (*GetStripePlansResponse, error)
}

type bFFServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBFFServiceClient(cc grpc.ClientConnInterface) BFFServiceClient {
	return &bFFServiceClient{cc}
}

func (c *bFFServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, BFFService_GetUserInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BFFService_ServiceDesc.Streams[0], BFFService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BFFService_ChatClient = grpc.ServerStreamingClient[ChatEvent]

func (c *bFFServiceClient) StopChat(ctx context.Context, in *StopChatRequest, opts ...grpc.CallOption) (*StopChatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopChatResponse)
	err := c.cc.Invoke(ctx, BFFService_StopChat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GenerateTitle(ctx context.Context, in *GenerateTitleRequest, opts ...grpc.CallOption) (*GenerateTitleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateTitleResponse)
	err := c.cc.Invoke(ctx, BFFService_GenerateTitle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetChatIds(ctx context.Context, in *GetChatIdsRequest, opts ...grpc.CallOption) (*GetChatIdsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatIdsResponse)
	err := c.cc.Invoke(ctx, BFFService_GetChatIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetChatHistory(ctx context.Context, in *GetChatHistoryRequest, opts ...grpc.CallOption) (*GetChatHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatHistoryResponse)
	err := c.cc.Invoke(ctx, BFFService_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetChatContext(ctx context.Context, in *GetChatContextRequest, opts ...grpc.CallOption) (*GetChatContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChatContextResponse)
	err := c.cc.Invoke(ctx, BFFService_GetChatContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetLLMModels(ctx context.Context, in *GetLLMModelsRequest, opts ...grpc.CallOption) (*GetLLMModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMModelsResponse)
	err := c.cc.Invoke(ctx, BFFService_GetLLMModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetMcpInfo(ctx context.Context, in *GetMcpInfoRequest, opts ...grpc.CallOption) (*GetMcpInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMcpInfoResponse)
	err := c.cc.Invoke(ctx, BFFService_GetMcpInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetMcpForUser(ctx context.Context, in *GetMcpForUserRequest, opts ...grpc.CallOption) (*GetMcpForUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMcpForUserResponse)
	err := c.cc.Invoke(ctx, BFFService_GetMcpForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) SelectMcp(ctx context.Context, in *SelectMcpRequest, opts ...grpc.CallOption) (*SelectMcpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectMcpResponse)
	err := c.cc.Invoke(ctx, BFFService_SelectMcp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetUserSettings(ctx context.Context, in *GetUserSettingsRequest, opts ...grpc.CallOption) (*GetUserSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserSettingsResponse)
	err := c.cc.Invoke(ctx, BFFService_GetUserSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) QueryRateLimit(ctx context.Context, in *QueryRateLimitRequest, opts ...grpc.CallOption) (*QueryRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRateLimitResponse)
	err := c.cc.Invoke(ctx, BFFService_QueryRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetStripeSubscription(ctx context.Context, in *GetStripeSubscriptionRequest, opts ...grpc.CallOption) (*GetStripeSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStripeSubscriptionResponse)
	err := c.cc.Invoke(ctx, BFFService_GetStripeSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bFFServiceClient) GetStripePlans(ctx context.Context, in *GetStripePlansRequest, opts ...grpc.CallOption) (*GetStripePlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStripePlansResponse)
	err := c.cc.Invoke(ctx, BFFService_GetStripePlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BFFServiceServer is the server API for BFFService service.
// All implementations must embed UnimplementedBFFServiceServer
// for forward compatibility.
//
// BFFService provides backend-for-frontend operations
type BFFServiceServer interface {
	// User info
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// Chat operations (streaming for CLI)
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error
	StopChat(context.Context, *StopChatRequest) (*StopChatResponse, error)
	GenerateTitle(context.Context, *GenerateTitleRequest) (*GenerateTitleResponse, error)
	// Query operations
	GetChatIds(context.Context, *GetChatIdsRequest) (*GetChatIdsResponse, error)
	GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error)
	GetChatContext(context.Context, *GetChatContextRequest) (*GetChatContextResponse, error)
	GetLLMModels(context.Context, *GetLLMModelsRequest) (*GetLLMModelsResponse, error)
	GetMcpInfo(context.Context, *GetMcpInfoRequest) (*GetMcpInfoResponse, error)
	GetMcpForUser(context.Context, *GetMcpForUserRequest) (*GetMcpForUserResponse, error)
	SelectMcp(context.Context, *SelectMcpRequest) (*SelectMcpResponse, error)
	GetUserSettings(context.Context, *GetUserSettingsRequest) (*GetUserSettingsResponse, error)
	QueryRateLimit(context.Context, *QueryRateLimitRequest) (*QueryRateLimitResponse, error)
	// Stripe/Billing operations
	GetStripeSubscription(context.Context, *GetStripeSubscriptionRequest) (*GetStripeSubscriptionResponse, error)
	GetStripePlans(context.Context, *GetStripePlansRequest) (*GetStripePlansResponse, error)
	mustEmbedUnimplementedBFFServiceServer()
}

// UnimplementedBFFServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBFFServiceServer struct{}

func (UnimplementedBFFServiceServer) GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (UnimplementedBFFServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatEvent]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedBFFServiceServer) StopChat(context.Context, *StopChatRequest) (*StopChatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopChat not implemented")
}
func (UnimplementedBFFServiceServer) GenerateTitle(context.Context, *GenerateTitleRequest) (*GenerateTitleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateTitle not implemented")
}
func (UnimplementedBFFServiceServer) GetChatIds(context.Context, *GetChatIdsRequest) (*GetChatIdsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatIds not implemented")
}
func (UnimplementedBFFServiceServer) GetChatHistory(context.Context, *GetChatHistoryRequest) (*GetChatHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedBFFServiceServer) GetChatContext(context.Context, *GetChatContextRequest) (*GetChatContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChatContext not implemented")
}
func (UnimplementedBFFServiceServer) GetLLMModels(context.Context, *GetLLMModelsRequest) (*GetLLMModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLLMModels not implemented")
}
func (UnimplementedBFFServiceServer) GetMcpInfo(context.Context, *GetMcpInfoRequest) (*GetMcpInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMcpInfo not implemented")
}
func (UnimplementedBFFServiceServer) GetMcpForUser(context.Context, *GetMcpForUserRequest) (*GetMcpForUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMcpForUser not implemented")
}
func (UnimplementedBFFServiceServer) SelectMcp(context.Context, *SelectMcpRequest) (*SelectMcpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelectMcp not implemented")
}
func (UnimplementedBFFServiceServer) GetUserSettings(context.Context, *GetUserSettingsRequest) (*GetUserSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserSettings not implemented")
}
func (UnimplementedBFFServiceServer) QueryRateLimit(context.Context, *QueryRateLimitRequest) (*QueryRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryRateLimit not implemented")
}
func (UnimplementedBFFServiceServer) GetStripeSubscription(context.Context, *GetStripeSubscriptionRequest) (*GetStripeSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStripeSubscription not implemented")
}
func (UnimplementedBFFServiceServer) GetStripePlans(context.Context, *GetStripePlansRequest) (*GetStripePlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStripePlans not implemented")
}
func (UnimplementedBFFServiceServer) mustEmbedUnimplementedBFFServiceServer() {}
func (UnimplementedBFFServiceServer) testEmbeddedByValue()                    {}

// UnsafeBFFServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BFFServiceServer will
// result in compilation errors.
type UnsafeBFFServiceServer interface {
	mustEmbedUnimplementedBFFServiceServer()
}

func RegisterBFFServiceServer(s grpc.ServiceRegistrar, srv BFFServiceServer) {
	// If the following call panics, it indicates UnimplementedBFFServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BFFService_ServiceDesc, srv)
}

func _BFFService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetUserInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BFFServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BFFService_ChatServer = grpc.ServerStreamingServer[ChatEvent]

func _BFFService_StopChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).StopChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_StopChat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).StopChat(ctx, req.(*StopChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GenerateTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GenerateTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GenerateTitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GenerateTitle(ctx, req.(*GenerateTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetChatIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetChatIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetChatIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetChatIds(ctx, req.(*GetChatIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetChatHistory(ctx, req.(*GetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetChatContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChatContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetChatContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetChatContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetChatContext(ctx, req.(*GetChatContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetLLMModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetLLMModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetLLMModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetLLMModels(ctx, req.(*GetLLMModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetMcpInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMcpInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetMcpInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetMcpInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetMcpInfo(ctx, req.(*GetMcpInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetMcpForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMcpForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetMcpForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetMcpForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetMcpForUser(ctx, req.(*GetMcpForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_SelectMcp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectMcpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).SelectMcp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_SelectMcp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).SelectMcp(ctx, req.(*SelectMcpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetUserSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetUserSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetUserSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetUserSettings(ctx, req.(*GetUserSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_QueryRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).QueryRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_QueryRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).QueryRateLimit(ctx, req.(*QueryRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetStripeSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStripeSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetStripeSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetStripeSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetStripeSubscription(ctx, req.(*GetStripeSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BFFService_GetStripePlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStripePlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BFFServiceServer).GetStripePlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BFFService_GetStripePlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BFFServiceServer).GetStripePlans(ctx, req.(*GetStripePlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BFFService_ServiceDesc is the grpc.ServiceDesc for BFFService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BFFService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bff.v1.BFFService",
	HandlerType: (*BFFServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _BFFService_GetUserInfo_Handler,
		},
		{
			MethodName: "StopChat",
			Handler:    _BFFService_StopChat_Handler,
		},
		{
			MethodName: "GenerateTitle",
			Handler:    _BFFService_GenerateTitle_Handler,
		},
		{
			MethodName: "GetChatIds",
			Handler:    _BFFService_GetChatIds_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _BFFService_GetChatHistory_Handler,
		},
		{
			MethodName: "GetChatContext",
			Handler:    _BFFService_GetChatContext_Handler,
		},
		{
			MethodName: "GetLLMModels",
			Handler:    _BFFService_GetLLMModels_Handler,
		},
		{
			MethodName: "GetMcpInfo",
			Handler:    _BFFService_GetMcpInfo_Handler,
		},
		{
			MethodName: "GetMcpForUser",
			Handler:    _BFFService_GetMcpForUser_Handler,
		},
		{
			MethodName: "SelectMcp",
			Handler:    _BFFService_SelectMcp_Handler,
		},
		{
			MethodName: "GetUserSettings",
			Handler:    _BFFService_GetUserSettings_Handler,
		},
		{
			MethodName: "QueryRateLimit",
			Handler:    _BFFService_QueryRateLimit_Handler,
		},
		{
			MethodName: "GetStripeSubscription",
			Handler:    _BFFService_GetStripeSubscription_Handler,
		},
		{
			MethodName: "GetStripePlans",
			Handler:    _BFFService_GetStripePlans_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _BFFService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bff.proto",
}
